# This configuration uses yaml as the replacement for JSON file for configuation purposes:

---
namespace: Remote test of pages
repository: public/remote/pages
repositoryURL: http://localhost:8080/remote/pages/
intents:  public/remote/intents
intentsURL: http://localhost:8080/remote/intents
displays: public/remote/displays
displaysURL: http://localhost:8080/remote/displays
output: yaml
# Set this to true if you want to have also URL-s mapped in the local command line client:
mapURL: true
pageName: {{random}}
keys:
  - ii20319hkjasoudoi2iupi1902u4nvbjtoo
  - iuiurhfbjhdsfu23hyh8919289yhr98auso
